name: main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform fmt check
      working-directory: ./terraform
      run: terraform fmt -check

    - name: Terraform validate
      working-directory: ./terraform
      run: terraform validate

    - name: Terraform plan
      working-directory: ./terraform
      run: terraform plan -lock=true -input=false -out=.terraform/tfplan -var 'environment=production'

    - name: Terraform apply
      if: github.event_name == 'push'
      working-directory: ./terraform
      run: terraform apply -lock=true -input=false -auto-approve .terraform/tfplan
