name: main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.16
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform fmt check
      working-directory: ./terraform
      run: terraform fmt -check

    - name: Terraform validate
      working-directory: ./terraform
      run: terraform validate

    - name: Terraform plan
      working-directory: ./terraform
      run: terraform plan -lock=true -input=false -out=.terraform/tfplan -var 'environment=production'

    - name: Terraform apply
      if: github.event_name == 'push'
      working-directory: ./terraform
      run: terraform apply -lock=true -input=false -auto-approve .terraform/tfplan

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.73.0'
        extended: true

    - name: Build static site
      working-directory: ./hugo
      run: hugo --minify

    - name: Upload site
      if: github.event_name == 'push'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ./hugo
      run: aws s3 sync public s3://replisims-production-website
